### PR TITLE
remove exception on label starting with number

### PR DESCRIPTION
**Pull request by EvaLok**
labels may start with numbers (or be entirely numbers) as per rfc1123 (ref: http://tools.ietf.org/html/rfc1123#page-13)

### CODE REVIEW

**Comment by EvaLok** [comment]
i see this failed a unit test (obviously). i'll wait for confirmation that i'm indeed interpreting that RFC doc correctly, and if so i'll fix it

**Comment by nyamsprod** [comment]
Hi @EvaLok 
you are right after reviewing [RFC3986](http://tools.ietf.org/html/rfc3986#section-3.2.2) host labels can be entirely numbers. for instance this website exists and is valid [www.11.be](http://www.11.be). 

So if you can update your tests I'll accept the PR.

**Comment by nyamsprod** [comment]
@EvaLok any news ?

**Comment by EvaLok** [comment]
@nyamsprod sorry, i've been busy busy with work, but i'll certainly update the tests and resubmit the PR this weekend :)

**Comment by nyamsprod** [comment]
@EvaLok  okay thanks I think that's the last thing to check before having a v4 beta out

**Comment by EvaLok** [comment]
@nyamsprod OK i updated the tests; i'm not 100% sure that `//80` is a valid url, but i re-reviewed the RFC and it says that labels can be entirely numeric, so i suppose it is.. certainly may want to triple-check this one though ;)

**Comment by nyamsprod** [comment]
yes as strange as it is  `//80` is a valid host thanks for the fix

**Pull request merged**
