### PR TITLE
Added inline fix for https://bugs.php.net/bug.php?id=68917

### PR DESCRIPTION
**Pull request by stepanselyuk**

### CODE REVIEW

**Comment by stepanselyuk** [comment]
Related to issue #65

**Comment by nyamsprod** [comment]
you made the PR against v4 ... which is not out yet ... you should PR against the develop-3 branch if you want the patch to be made available on v3.
Also you need to update the test suite. Please follow the [contribute.md](https://github.com/thephpleague/url/blob/master/CONTRIBUTING.md) doc

**Comment by stepanselyuk** [comment]
Oops I want to contribute for 3.x. My bad.

**Comment by nyamsprod** [comment]
Ok in the meantime I've backported you code in v4 with the tests and all

**Pull request closed without merging**
