### PR TITLE
Fix for issue #51.   Stop runtime error being thrown when FQDN is used.

### PR DESCRIPTION
**Pull request by equinoxmatt**

### CODE REVIEW

**Comment by nyamsprod** [comment]
Hi 
some quick remarks.
- Could you please follow the contribution rules which states to have PSR-2 coding style and a passing test

- AbstractSegment shouldn't have a special case for a special delimiter I think you should move your modification in the Host class directly.

**Comment by equinoxmatt** [comment]
Hello,

1) Yeah I was hesitant about submitting with the changes in the AbstractSegment, however when I made any changes in the Host Class, it was causing problems in other tests.  I will take another look because I understand where you are coming from.

2) There is a test,  however it has no assertion, it passes through a FQDN to createFromServer() and fails when a runtime exception is triggered.  I could 'assert' the object is valid, however the test is meant to show you can pass FQDN through and throw an exception.

**Comment by equinoxmatt** [comment]
The issue is validateSegment() explodes the string, on either '/' or '.' delimiter.   My original approach of removing the dot is no good.  It needs to keep the dot.  Maybe someone else can have a go at solving this :)

**Comment by nyamsprod** [comment]
Ok, no problem I'll try to solve this issue in v4 thanks anyway. I'll let you know when this is fix

**Pull request closed without merging**
