### PR TITLE
Update package name from "URL" to "URI"

### PR DESCRIPTION
**Pull request by hansott**

### CODE REVIEW

**Comment by nyamsprod** [comment]
@hansott I have some reservation about this change.

To be honest I am more and more thinking about breaking the relation between League\Uri and League\Url to clearly mark the distinction between both package. Changing the naming right now would confuse even more people IMHO. I think a better approach is to leave v3 documentation on url.thephpleague.com and move the documentation for v4 onto a new subdomain uri.thephpleague.com.

What do you think ?

**Comment by hansott** [comment]
Sounds fantastic. :+1: Thanks for your view on the matter.

**Comment by nyamsprod** [comment]
Both packages are now totally separated. Thanks for submitting it anyway :+1:

**Comment by hansott** [comment]
:tada:

**Pull request closed without merging**
